#!/usr/bin/env bash
# fetch_libsodium.sh — vendor a pinned, verified libsodium source tree.
#
# The seal (src/storage/trusted_storage.cpp) uses libsodium's Argon2id KDF and
# XChaCha20-Poly1305 AEAD. We build libsodium from source rather than home-roll
# crypto. This script downloads a pinned release, verifies its SHA256, extracts
# it into third_party/libsodium/, and drops in the pre-generated version.h so the
# tree compiles WITHOUT autotools (`configure`) — see build.sh, which globs the
# .c files. Portable C is selected because the autotools HAVE_* feature macros
# are absent, so no per-file -march tuning is required.
#
# The source is NOT committed (see .gitignore); run this once after checkout.
# Re-running is idempotent (skips if the version is already present and valid).
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="1.0.20"
SHA256="ebb65ef6ca439333c2bb41a0c1990587288da07f6c7fd07cb3a18cc18d30ce19"
URL="https://download.libsodium.org/libsodium/releases/libsodium-${VERSION}.tar.gz"

DEST="third_party/libsodium"
SRC="${DEST}/libsodium-${VERSION}"
STAMP="${SRC}/.vendored-ok"

if [ -f "$STAMP" ]; then
    echo "libsodium ${VERSION} already vendored at ${SRC}"
    exit 0
fi

mkdir -p "$DEST"
TARBALL="${DEST}/libsodium-${VERSION}.tar.gz"

echo "downloading libsodium ${VERSION} ..."
curl -sSL -o "$TARBALL" "$URL"

echo "verifying SHA256 ..."
if command -v sha256sum >/dev/null 2>&1; then
    echo "${SHA256}  ${TARBALL}" | sha256sum -c - || {
        echo "ERROR: SHA256 mismatch for $TARBALL" >&2; rm -f "$TARBALL"; exit 1; }
elif command -v shasum >/dev/null 2>&1; then
    echo "${SHA256}  ${TARBALL}" | shasum -a 256 -c - || {
        echo "ERROR: SHA256 mismatch for $TARBALL" >&2; rm -f "$TARBALL"; exit 1; }
else
    echo "WARN: no sha256sum/shasum found; skipping integrity check" >&2
fi

echo "extracting ..."
rm -rf "$SRC"
tar -xzf "$TARBALL" -C "$DEST"

# version.h is normally generated by ./configure from version.h.in. The release
# ships a pre-generated copy for the MSVC build that is identical for our needs
# (portable build, no minimal flag); drop it into the include tree.
cp "${SRC}/builds/msvc/version.h" "${SRC}/src/libsodium/include/sodium/version.h"

rm -f "$TARBALL"
touch "$STAMP"
echo "libsodium ${VERSION} vendored -> ${SRC}"
